# Generated by Django 3.1.7 on 2021-03-08 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import url_shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(verbose_name='Long URL')),
                ('short_url', models.URLField(default=url_shortener.models.generate_short_url, unique=True, verbose_name='Short URL')),
                ('last_validation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Validation')),
                ('is_broken', models.BooleanField(blank=True, default=False, verbose_name='Status of link')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Short_Links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
